In [92]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1


## Intro to Tensors

### Creating Tensors



In [93]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [94]:
scalar.ndim

0

In [95]:
scalar.item()

7

In [96]:
# Vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [97]:
vector.ndim

1

In [98]:
vector.shape

torch.Size([2])

In [99]:
# MATRIX
MATRIX = torch.tensor([[7,8],
                       [9,10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [100]:
MATRIX.ndim

2

In [101]:
MATRIX[0]

tensor([7, 8])

In [102]:
MATRIX.shape

torch.Size([2, 2])

In [103]:
# Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,5],
                        [3,6,8]]])

TENSOR

tensor([[[1, 2, 3],
         [3, 6, 5],
         [3, 6, 8]]])

In [104]:
TENSOR.ndim

3

In [105]:
TENSOR.shape

torch.Size([1, 3, 3])

In [106]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 5],
        [3, 6, 8]])

### Random tensors

In [107]:
# Create random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [108]:
random_tensor.ndim

2

In [109]:
# Create random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [110]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [111]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [112]:
# Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [113]:
ones.dtype

torch.float32

### Creating a range of tensors

In [114]:
# user torch.arange()
one_to_ten = torch.arange(start=0,end=1000, step=77)
one_to_ten

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

# Creating tensors-like

In [115]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [116]:
ten_randos = torch.ones_like(input=one_to_ten)

### Tensor datatypes

In [117]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0 ,6.0, 9.0],
                               dtype=None, # eg. torch.float_16
                               device=None,
                               requires_grad=False)

In [118]:
float_32_tensor.dtype

torch.float32

In [119]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [120]:
float_16_tensor * float_32_tensor # sometimes it works anyway

tensor([ 9., 36., 81.])

In [121]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [122]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating Tensors (tensor operations)

- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication

In [123]:
# Create tensor
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [124]:
tensor - 10

tensor([-9, -8, -7])

In [125]:
tensor * 10

tensor([10, 20, 30])

In [126]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [127]:
# PyTorch built-in functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [128]:
torch.add(tensor, 3)

tensor([4, 5, 6])

### Matrix multiplcation

2 main methods in nn and dlink

- Element-wise (scalar)
- Matrix multiplication (dot product)

In [129]:
tensor1 = torch.tensor([[1,2],[3,4]])
tensor2 = torch.tensor([[0,1],[1,0]])
tensor1 * tensor2

tensor([[0, 2],
        [3, 0]])

In [130]:
# scalar
tensor * tensor

tensor([1, 4, 9])

In [131]:
# dot product
torch.matmul(tensor, tensor)

tensor(14)

### Shapes for matrix multiplication

In [132]:
tensor1 = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor2 = torch.tensor([[7,10],
                        [8,11],
                        [9,12]])



## Transpose

In [133]:
# switch axes
torch.mm(tensor1, tensor2.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [134]:
torch.mm(tensor1, tensor1.T)

tensor([[ 5, 11, 17],
        [11, 25, 39],
        [17, 39, 61]])

In [135]:
tensor1

tensor([[1, 2],
        [3, 4],
        [5, 6]])

## Aggregation: min, max, mean, sum, etc

In [136]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [137]:
x.min

<function Tensor.min>

In [138]:
x.min()

tensor(0)

In [139]:
x.max()

tensor(90)

In [140]:
x.sum()

tensor(450)

In [141]:
x.dtype

torch.int64

In [142]:
# convert integers for mean calculations

torch.mean(x.type(torch.float32))

tensor(45.)

In [143]:
x.type(torch.float32).mean()

tensor(45.)

## Positional min/max

In [144]:
x.argmax()


tensor(9)

In [145]:
x.argmin()

tensor(0)

## Reshaping, stacking, squeezing and unsqueezing

* Reshape - obvious
* View - Return a view of input tensor of a certain shape but keep the same memory as the original tensor
* Stacking - vstack or hstack
* Squeeze - removes all `1` dimensions
* Unsqueeze - add a `1` dimension
* Permute - return a view with dimensions permuted (swapped) in a certain way

In [146]:
import torch
x = torch.arange(1.,11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [147]:
x_reshaped = x.reshape(2,5)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.],
         [ 6.,  7.,  8.,  9., 10.]]),
 torch.Size([2, 5]))

In [148]:
x_reshaped = x.reshape(5,2)
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]),
 torch.Size([5, 2]))

In [149]:
x = torch.arange(1.,10.)
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [150]:
# Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [151]:
# Changing z changes x (z shares memory with input)
z[:,0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [152]:
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [153]:
# Stack tensors on top
x_stacked = torch.stack([x,x,x,x]) # default dim=0
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [154]:
# Squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

x_squeezed = x_reshaped.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [155]:
# Unsqueeze - adds a single dimension to a target tensor at a specific dim
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

x_unsqueezed = x_squeezed.unsqueeze(dim=0)

print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [156]:
# Permute - swapping rows and columns
x_original = torch.rand(size=(224,224,3))

x_permuted = x_original.permute(2,0,1) # shifts 2->0, 0->1, 1->2

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [157]:
x_original.shape

torch.Size([224, 224, 3])

## Indexing (selecting data from tensors)

In [158]:
# Create a tensor
import torch
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [159]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [160]:
x[0,0] # same as x[0][0]

tensor([1, 2, 3])

In [161]:
x[0,0,0]

tensor(1)

In [162]:
# : selects "all" of target dimension
x[:,:,2]

tensor([[3, 6, 9]])

In [163]:
x[:,:,2].squeeze()

tensor([3, 6, 9])

## NumPy
- Convert NumPy data to Pytorch tensor `torch.from_numpy(ndarray)`
- Conver tensor to NumPy `torch.Tensor.numpy()`

In [164]:
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)#numpy default is 64 .type(torch.float32) change
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [165]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

To reduce the randomness in neural networks use **random seed* (salt)


In [166]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_B == random_tensor_A)

tensor([[0.3588, 0.9211, 0.8627, 0.8223],
        [0.5248, 0.5881, 0.2746, 0.3791],
        [0.2975, 0.6450, 0.0163, 0.9160]])
tensor([[0.5888, 0.8403, 0.4761, 0.7140],
        [0.4644, 0.6362, 0.8892, 0.1317],
        [0.7164, 0.2706, 0.6560, 0.6614]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [167]:
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [168]:
tensor.device

device(type='cpu')

In [186]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [187]:
input = tensor.to(device)

In [188]:
print(input, input.device)

tensor([1, 2, 3], device='cuda:0') cuda:0


In [189]:
!nvidia-smi

Sun Dec 18 11:35:53 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 510.85.02    Driver Version: 510.85.02    CUDA Version: 11.6     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P0    N/A /  N/A |    355MiB /  2048MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [190]:
torch.cuda.is_available()

True

In [191]:
 # Count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on gpu

In [192]:
tensor = torch.tensor([1,2,3])
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [195]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [196]:
new_tensor = torch.tensor([2,3,4], device=device)

In [197]:
new_tensor

tensor([2, 3, 4], device='cuda:0')

In [ ]:
# Must convert to cpu for numpy

In [198]:
tensor_back_to_cpu = new_tensor.cpu().numpy()
tensor_back_to_cpu

array([2, 3, 4])