# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading 

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [19]:
# Import torch

import torch


# Create random tensor

X = torch.rand(size=(7,7))
X, X.shape

(tensor([[0.3522, 0.0198, 0.7723, 0.0325, 0.3183, 0.7286, 0.5767],
         [0.9089, 0.9563, 0.4963, 0.8146, 0.2043, 0.8455, 0.6038],
         [0.9838, 0.3668, 0.3865, 0.3082, 0.7055, 0.3799, 0.6296],
         [0.8151, 0.8737, 0.7807, 0.4450, 0.4218, 0.2459, 0.7415],
         [0.1020, 0.6174, 0.1271, 0.6017, 0.0978, 0.4809, 0.0284],
         [0.8017, 0.3375, 0.2397, 0.1860, 0.8090, 0.9646, 0.2777],
         [0.0024, 0.7606, 0.7547, 0.0422, 0.9219, 0.6868, 0.1962]]),
 torch.Size([7, 7]))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [20]:
# Create another random tensor
Y = torch.rand(size=(1,7))

# Perform matrix multiplication 

Z = torch.matmul(X, Y.T)
Z, Z.shape

(tensor([[1.3639],
         [1.9556],
         [1.9175],
         [1.7410],
         [0.6635],
         [1.9501],
         [1.3707]]),
 torch.Size([7, 1]))

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [26]:
# Set manual seed
torch.manual_seed(0)


# Create two random tensors

S = torch.rand(size=(7,7))
T = torch.rand(size=(1,7))
U = torch.matmul(S, T.T)
U, U.size()

# Matrix multiply tensors


(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [27]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [30]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Device: {device}")

# Create two random tensors on GPU
A = torch.rand(size=(2,3)).to(device)
B = torch.rand(size=(2,3)).to(device)
A, B


Device: cuda


(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [32]:
# Perform matmul on tensor_A and tensor_B
C = torch.matmul(A, B.T)
C, C.size()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [36]:
# Find max
max = C.max()
min = C.min()
print(f"max: {max}, min: {min}")
# Find min


max: 0.5617256760597229, min: 0.3647301495075226


### 9. Find the maximum and minimum index values of the output of 7.

In [39]:
# Find arg max
arg_max = C.argmax()
arg_min = C.argmin()
arg_max, arg_min

# Find arg min


(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [41]:
# Set seed
torch.manual_seed(7)

# Create random tensor
B = torch.rand(size=(1,1,1,10))

# Remove single dimensions
B.squeeze

# Print out tensors and their shapes


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])