# NumPy

[Python NumPy Tutorial](https://www.youtube.com/watch?v=QUT1VHiLmmI)

[NumPy](https://numpy.org/doc/stable/reference/index.html)

## Basics

In [1]:
import numpy as np
import sys

**Create arrays**

In [34]:
a = np.array([1,2,3], dtype='int16') # dtype defaults to int64
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]])
print(a)
print(b)

[1 2 3]
[[1. 2. 3.]
 [4. 5. 6.]]


**Array information**
- dimension (number of nesting levels)
- shape (number of rows and columns)
- type (data type of elements)
- size (total number of elements)
- itemsize (number of bytes occupied by each element)
- nbytes (total number of bytes for the array)


In [36]:
print(f"Dimensions (a): {a.ndim} | Dimensions (b): {b.ndim}")
print(f"Type (a): {a.dtype} | Type (b): {b.dtype}")
print(f"Size (a): {a.size} | (b): {b.size}")
print(f"Shape (a): {a.shape} | (b): {b.shape}")
print(f"Item Size (a): {a.itemsize} | (b): {b.itemsize}")
print(f"Total bytes (a): {a.nbytes} | (b): {b.nbytes}")

Dimensions (a): 1 | Dimensions (b): 2
Type (a): int16 | Type (b): float64
Size (a): 3 | (b): 6
Shape (a): (3,) | (b): (2, 3)
Item Size (a): 2 | (b): 8
Total bytes (a): 6 | (b): 48


**Accessing/Changing specific elements, rows, columns, etc**

In [42]:
a = np.array([[1,2,3,4,5,6,7],[8,1,10,11,12,13,14]]) # zero based indexing

*Specific Element*

In [44]:
print(a[1,3])
print(a[0,-2])

11
6


*Specific Row or Column*

In [49]:
print(a[0,:])
print(a[:,2])

[1 2 3 4 5 6 7]
[ 3 10]


*Select with `[startindex:endindex:step]`*

In [50]:
a[0,1:6:2]

array([2, 4, 6])

*Change data*

In [52]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  1 10 11 12 20 14]]


In [54]:
a[:,2] = 33
print(a)

[[ 1  2 33  4  5  6  7]
 [ 8  1 33 11 12 20 14]]


In [55]:
a[:,2] = [51,52]
print(a)

[[ 1  2 51  4  5  6  7]
 [ 8  1 52 11 12 20 14]]


*3d Example*

In [69]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [70]:
b[0,1,1] # order outside in)

4

In [71]:
print(b[:,1,:])



[[3 4]
 [7 8]]


In [72]:
b[:,1,:] = [[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

**Initializing Different Types of Arrays**
- zeros
- ones
- full (specify a number for all elements)
- full_like (use an already existing array shape)
- random.rand
- random.randint
- random.random_sample (assigns random numbers to existing array shape)
- identity

In [73]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [84]:
np.ones((2,2,3), dtype='int16') # Can specify data type

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int16)

In [85]:
np.full((2,3), 99)

array([[99, 99, 99],
       [99, 99, 99]])

In [86]:
np.full_like(a, 4) # reuse existing array shape (same as np.full(a.shape, 4))

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [87]:
np.random.rand(2,2,3)

array([[[0.64349382, 0.82589095, 0.32413938],
        [0.054168  , 0.72098964, 0.21621908]],

       [[0.7251197 , 0.26086827, 0.73834044],
        [0.13729957, 0.87848384, 0.81641674]]])

In [88]:
np.random.random_sample(a.shape)

array([[0.08913158, 0.5405219 , 0.95980838, 0.33400565, 0.25517244,
        0.83676205, 0.91684218],
       [0.63577718, 0.76969313, 0.33470089, 0.26119458, 0.2323317 ,
        0.87221566, 0.45397428]])

In [97]:
print(np.random.randint(77, size=(3,3))) # if only one argument it is "high"
print(np.random.randint(1,7,size=(3,3))) # if not the first is "low"

[[ 0 17 28]
 [17 10 71]
 [60 31  6]]
[[2 4 5]
 [6 4 1]
 [3 4 2]]


In [98]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [101]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3) # default axis=1
r2 = np.repeat(arr,3,axis=0)
print(r1)
print(r2)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [134]:
narr = np.ones((5,5))
narr[1:4,1:4] = np.zeros((3,3))
narr[2,2] = 9
print(narr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


***Caution: if creating a copy with a = b you actually create a reference***

In [138]:
a = np.array([1,2,3])
b = a
print(a,b)
b[0] = 100
print(a,b)

[1 2 3] [1 2 3]
[100   2   3] [100   2   3]


In [139]:
a = np.array([1,2,3])
b = a.copy()
print(a,b)
b[0] = 100
print(a,b)

[1 2 3] [1 2 3]
[1 2 3] [100   2   3]


## Mathematics

### Algebraic functions

https://numpy.org/doc/stable/reference/routines.math.html#sums-products-differences

In [177]:
a = np.array([1,2,3,4])

In [178]:
a+2

array([3, 4, 5, 6])

In [179]:
a-2

array([-1,  0,  1,  2])

In [180]:
a*2

array([2, 4, 6, 8])

In [181]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [182]:
a ** 2

array([ 1,  4,  9, 16])

In [183]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

### Trig functions

https://numpy.org/doc/stable/reference/routines.math.html#trigonometric-functions

In [184]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [185]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

### Linear Algebra

https://numpy.org/doc/stable/reference/routines.linalg.html

In [186]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a, b)

[[1. 1. 1.]
 [1. 1. 1.]] [[2 2]
 [2 2]
 [2 2]]


#### Matrix multiplication

In [187]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

#### Deterimant

In [237]:
id = np.identity(3)
np.linalg.det(id)

1.0

#### Inverse
https://numpy.org/doc/stable/reference/generated/numpy.matrix.I.html

In [198]:
c = np.matrix('[1,2;3,4]')
c.getI()
c * c.getI()

matrix([[1.00000000e+00, 1.11022302e-16],
        [0.00000000e+00, 1.00000000e+00]])

### Statistics

In [211]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [212]:
np.min(stats)

1

In [215]:
np.max(stats, axis=1)

array([3, 6])

In [216]:
np.max(stats, axis=0)

array([4, 5, 6])

In [217]:
np.sum(stats)

21

In [218]:
np.sum(stats, axis=0)

array([5, 7, 9])

In [219]:
np.sum(stats, axis=1)

array([ 6, 15])

## Reorganizing Arrays

### Reshaping

In [225]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [230]:
after = before.reshape((4,2)); after

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [231]:
after = before.reshape((2,2,2)); after

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

### Stacking

In [233]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1, v2, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [236]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(h1, h2)
np.hstack([h1, h2])

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] [[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

### Load data from file

### Boolean Masking and Advanced indexing

In [246]:
data = np.array([[1,13,21,11,196,75,4,3,34,6,7,8,0,1,2,3,4,5],
                 [3,42,12,33,766,75,4,55,6,4,3,4,5,6,7,0,11,12],
                 [1,22,33,11,999,11,2,1,78,0,1,2,9,8,7,1,76,88]]); data

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

In [247]:
data > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [248]:
data[data>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [249]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [250]:
np.any(data>50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [251]:
np.any(data>50, axis=1)

array([ True,  True,  True])

In [252]:
((data > 50) & (data<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [257]:
(~((data > 50) & (data<100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])